### ISSUE TITLE
Index file works but checking fails.

### ISSUE THREAD

**Issue by Flynntes** [sjparkinson/isitup.org#17]
Hey Sam!
I am aware that other users have had the same issue, but I am unable to find a fix. When I upload the code, the home page works fine, but if I try to check if a website is down, i just get a white page. I am running this on an Apache server. It may be in issue with the .htaccess file, but I am only using the one you supplied. Have you tested the code on an apache server? Any luck? I also thought the issue may lie in the settings file. Are there any settings in there that actually need to be changed? I am running the code on the root of the root of the server. I have also enabled errors in settings.php, but it does not echo any errors to the page. I am aware that you run your site on a lighttpd. I am going to start two local servers: and apache and a lighttpd server and see if it works on the lighttpd. Any thoughs? Sorry about all the questions. Awesome script as well! Thanks a ton! Flynn

**Comment by Flynntes** [comment]
Any news?

**Comment by sjparkinson** [comment]
Sorry for the slow response, I don't check in here too much.

I'm going to be updating this repo with the dockerised version of the application very soon which has a better/tested .htaccess.

**Comment by sjparkinson** [comment]
Have a look at [src/.htaccess][file]!

[file]: https://github.com/sjparkinson/isitup.org/blob/master/src/.htaccess
